name = "webapp"
compatibility_date = "2026-01-29"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "webapp-production"
database_id = "d59067a5-3234-4874-832c-b3c4b273b31a"
